apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: lion-json-endpoint
  annotations:
    scenarios.ai.sap.com/name: "lion-json-endpoint"
    scenarios.ai.sap.com/description: "Endpoint minimo para probar conexion desde SAP AI Core hacia una API externa"
    executables.ai.sap.com/name: "json-test-server"
    executables.ai.sap.com/description: "Servidor HTTP minimo desplegado como contenedor Docker en SAP AI Core"
  labels:
    scenarios.ai.sap.com/id: "lion-json-endpoint"
    executables.ai.sap.com/id: "lion-json-endpoint"
    ai.sap.com/version: "1.0.1"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kfserving-container
          image: docker.io/cyberneticintegrator/ai-core-api-probe:latest
          ports:
            - containerPort: 8080
              protocol: TCP
